name: Unit Tests
on: [push]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build internal dependencies
        run: yarn build-libs
      - name: Run Unit tests
        run: yarn test
  typeCheck:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build internal dependencies
        run: yarn build-libs
      - name: Run Unit tests
        run: yarn check-types
