name: Unit Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: 
        - '*'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Run Unit tests
        run: yarn test
